spring:
  application:
    name: producer
  kafka:
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  cloud:
    stream:
      bindings:
        pageViews-out-0:
          destination: page_views_topic

